### PR TITLE
Add CLI on agent

### PR DESCRIPTION
**Pull request by Razano26**

### CODE REVIEW

**Comment by Razano26** [comment]
Can't be test because mock schedule won’t work.

**Comment by hugoponthieu** [comment]
@theotchlx  I thougth i merged all the necessary but it disapeared. Let me check that. I m confused

**Comment by theotchlx** [comment]
LGTM. I tested your CLI and it works :) :+1:

**Review by theotchlx — APPROVED** [review]
LGTM. I tested your CLI and it works :) :+1:

**Pull request merged**
