### PR TITLE
Monitor error handling

### PR DESCRIPTION
**Pull request by hugoponthieu**
Using a single way to handle error in the external_api

### CODE REVIEW

**Review by isalyne34 — APPROVED** [review]
I think everything is good, however it's strange to have so many modifications related to lint if cargo was used correctly before

**Review by hugoponthieu — COMMENTED** [review]
Can be merged

**Review by je-suis-professionnelle — APPROVED** [review]
Seems good to me !

**Review by je-suis-professionnelle — CHANGES_REQUESTED** [review]
actually i noticed that it always write "new commit found" event if there is not a new commit, so there is a little problem here

**Pull request merged**
